### ISSUE TITLE
JSON.parse Error: Invalid character at position: 1268

### ISSUE THREAD

**Issue by WirthmU** [mcrossley/SteelSeries-Weather-Gauges#11]
Using Weather Display and latest version of SteelSeries-Weather-Gauges.

customclientraw.txt is continuously updated and looks like:

{"date":"21:13:25","dateFormat":"d/m/y","temp":"-2.5","tempTL":"-2.5","tempTH":"-2.5","intemp":"22.4","dew":"-4.5","dewpointTL":"-4.5","dewpointTH":"-4.5","apptemp":"-4.4","apptempTL":"-4.4","apptempTH":"-4.4","wchill":"-2.5","wchillTL":"-2.5","heatindex":"-2.5","heatindexTH":"-2.5","humidex":"-5.6","wlatest":"0.0","wspeed":"0.0","wgust":"0.0","wgustTM":"0.0","bearing":"0","avgbearing":"360","press":"949.0","pressTL":"948.0","pressTH":"953.0","pressL":"948.0","pressH":"953.0","rfall":"0.0","rrate":"0.0","rrateTM":"0.0","hum":"86","humTL":"86","humTH":"86","inhum":"42","inhumTL":"%minindoorhum%","inhumTH":"%maxindoorhum%","intempTL":"22.3","TintempTL":"%minindoortempt%","intempTH":"22.8","TintempTH":"%maxindoortempt%","SensorContactLost":"0","forecast":"---","tempunit":"C","windunit":"kmh","pressunit":"hPa","rainunit":"mm","temptrend":"0.0","TtempTL":"22:17","TtempTH":"22:17","TdewpointTL":"20:48","TdewpointTH":"22:17","TapptempTL":"20:48","TapptempTH":"22:17","TwchillTL":"22:17","TheatindexTH":"22:17","TrrateTM":"","ThourlyrainTH":"","LastRainTipISO":"------","hourlyrainTH":"0.0","ThumTL":"22:17","ThumTH":"22:17","TinhumTL":"%dailylowindoorhumtime%","TinhumTH":"%dailyhighindoorhumtime%","TpressTL":"18:41","TpressTH":"22:17","presstrendval":"-64.0 
","Tbeaufort":"0","TwgustTM":"","windTM":"0.0","bearingTM":"0","timeUTC":"2019,01,09,20,13,25","BearingRangeFrom10":"360","BearingRangeTo10":"360","UV":"0.0","UVTH":"0.0","SolarRad":"0","CurrentSolarMax":"0","SolarTM":"0","domwinddir":"Northerly","WindRoseData":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"windrun":"0.00","cloudbasevalue":"254","cloudbaseunit":"m","version":"WD_console_17.5","build":"---","ver":"14"}

The gauges update line shows a green LED and the following comment:

parsererror: SyntaxError: JSON.parse Error: Invalid character at position: 1268

Any help to this?

Thank you

**Comment by WirthmU** [comment]
Found the error - its been an editor issue entering <CR> characters to the customclientrawlocal.txt template.

**Comment by mcrossley** [comment]
I was going to say that you have a line break at character 1267.
Also WD is not processing all your tags. You would generally be better asking questions like this on the WD forum.

**Comment by WirthmU** [comment]
Brian told me that there is an unnecessary space in the customclientrawlocal.txt file (v2.7.0) right after ..3hour%:

","presstrendval":"%pressurechangein3hour% ","

Maybe you should correct that in the repository here.

**Comment by mcrossley** [comment]
I've updated the repo, but does that fix your problem? It seems to be unique to the version of WD you are using as no one else has reported this issue.

Also have you fixed WD not replacing lots of the tags in your file?

**Comment by WirthmU** [comment]
Removing the space resolved my error with JSON.parse. Thank you for correcting that.

I still got the problems with the tags. I will look for that with Brian.

Thank you for your support.
