### ISSUE TITLE
Added polish language

### ISSUE THREAD

**Issue by barcik75** [mcrossley/SteelSeries-Weather-Gauges#12]
Hi, I prepared language.min.js with polish language. Could you add to repository?
[language.min.js.zip](https://github.com/mcrossley/SteelSeries-Weather-Gauges/files/3013077/language.min.js.zip)

**Comment by mcrossley** [comment]
Thanks,

Ideally I would have liked the un-minimised version, but I can reformat
this...

Cheers
Mark

**Comment by mcrossley** [comment]
Published, thanks
