### ISSUE TITLE
Degrees symbol

### ISSUE THREAD

**Issue by WirthmU** [mcrossley/SteelSeries-Weather-Gauges#13]
I have seen that this has been an issue before. I have checked my html code, and it is UTF8. SteelSeries Gauges it the most recent (at least I think so)

I get the question mark instead of the ° symbol in the latest and average field for the wind bearing gauge. All other instances with the ° symbols are shown correct.

Any help to this?

**Comment by mcrossley** [comment]
Usual causes are not saving the script as UTF-8 after editing it, or using the script on a web page that is not using UTF-8 encoding.

**Comment by WirthmU** [comment]
That was it!

The file steelseries_tween.min.js was corrupt. I replaced it with the one from here and its all fine now.

Thank you for the support
