### ISSUE TITLE
Beginning with PHP 8.0 SSGauges fail

### ISSUE THREAD

**Issue by dehatter** [mcrossley/SteelSeries-Weather-Gauges#19]
When updating server PHP to 8.0 or 8.1 I get a parser error, incorrect syntax.  The background still displays but there are no values and the set will not update. Only a scrolling error message is shown in the banner.

**Comment by mcrossley** [comment]
What script are you using to generate the JSON for the gauges? The only one supplied with this package is "steelseriesVWSjson.php"

**Comment by dehatter** [comment]
So... looking to answer your question, it seems we are using a modified version.  Appears to be dated 2018 and has not been updated in a while.  I have attached  the files that are included in our package - so likely it is an issue with our template and not the series itself.  We have been getting very limited support as the developer is an individual and is working on a completely new version of the template - not much work on the existing one
[ssMeteotemplate.zip](https://github.com/mcrossley/SteelSeries-Weather-Gauges/files/9134160/ssMeteotemplate.zip)
.

**Comment by mcrossley** [comment]
Yep, looks like your problem will be somewhere in ssMeteotemplate.php

**Comment by dehatter** [comment]
A few people  - way more technical than me - have decided to work through it here at Meteotemplate.

Sorry to bother you.
