### ISSUE TITLE
Steel series throwing exceptions

### ISSUE THREAD

**Issue by DaveJ61** [mcrossley/SteelSeries-Weather-Gauges#2]
Hi,

I'm trying to install this skin but getting the exceptions/errors below. I'm running weewx 3.2.1 with owfs 0.17 on Ubuntu server 14.04.
I just wondered if you could see where the problem might be. Below I've uploaded a screenshot of the webpage, which is missing items most likely due to the exceptions.

![steelseries](https://cloud.githubusercontent.com/assets/1816367/10983397/32771990-840a-11e5-8199-b2f8a90e16c6.jpg)

Nov  5 21:55:31 localhost weewx[26275]: reportengine: Running report SteelSeries
Nov  5 21:55:31 localhost weewx[26275]: reportengine: Found configuration file /etc/weewx/skins/steelseries/skin.conf for report SteelSeries
Nov  5 21:55:31 localhost weewx[26275]: reportengine: copied 6 files to /var/www/html/weewx
Nov  5 21:55:31 localhost weewx[26275]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
Nov  5 21:55:31 localhost weewx[26275]: cheetahgenerator: ***\* Ignoring template /etc/weewx/skins/steelseries/gauge-data.txt.tmpl
Nov  5 21:55:31 localhost weewx[26275]: cheetahgenerator: ***\* Reason: unsupported operand type(s) for -: 'float' and 'NoneType'
Nov  5 21:55:31 localhost weewx[26275]: ***\*  Traceback (most recent call last):
Nov  5 21:55:31 localhost weewx[26275]: ***\*    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 294, in generate
Nov  5 21:55:31 localhost weewx[26275]: ***\*      print >> _file, text
Nov  5 21:55:31 localhost weewx[26275]: ***\*    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Nov  5 21:55:31 localhost weewx[26275]: ***\*      rc = getattr(self, mainMethName)()
Nov  5 21:55:31 localhost weewx[26275]: ***\*    File "_etc_weewx_skins_steelseries_gauge_data_txt_tmpl.py", line 190, in respond
Nov  5 21:55:31 localhost weewx[26275]: ***\*  TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Nov  5 21:55:31 localhost weewx[26275]: cheetahgenerator: Generated 1 files for report SteelSeries in 0.18 seconds
Nov  5 21:55:31 localhost weewx[26275]: genimages: Generated 11 images for SteelSeries in 0.39 seconds

Regards

David

**Comment by mcrossley** [comment]
Hi David,

I'm sorry, but I do not know anything much about weewx, the template file
gauge-data.txt.tmpl was supplied to me by Matthew Wall the author of weewx,
I suggest you contact him to see if he can resolve this issue for you.

Regards
Mark

**Comment by DaveJ61** [comment]
Hi Mark,

Thanks very much for getting back to me. I'll contact Matthew in this case then.
I'll update the issue to reflect this should anyone else come across this problem.

Thanks again,

David

**Comment by mcrossley** [comment]
Hi David, did you resolve this issue?
Mark

**Comment by DaveJ61** [comment]
Ah, many apologies Mark. I have resolved it yes. I used another download link and with a little tinkering, it all works. The only problem is I haven't got the link any more and I'm not sure if I can find it. If I do, then I will post it back on this issue, if it is still open. However, I'm guessing that it will be mark as resolved and closed.

**Comment by jovo0911** [comment]
Hi Mark,

i've similar issue and found a solution on google groups.
have a look to https://groups.google.com/forum/#!topic/weewx-user/rDdSbzQWbFw

after adding all the small hints up to post from gjr 27.5.2015 it works without sensordata (means with a lot of "none or N/A" in "gauge-data.txt"

Jochen

**Comment by mcrossley** [comment]
Thanks Jochen, I have incorporated the changes from that thread, I have incremented the release to 2.5.11.

**Comment by jovo0911** [comment]
you're welcome…. 

After I found the solution for my issue I think i should give that link to other or to the central place …. hope that help other .… 

have a nice day

Jochen

Am 12.01.2016 um 14:36 schrieb Mark Crossley notifications@github.com:

> Thanks Jochen, I have incorporated the changes from that thread, I have incremented the release to 2.5.11.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Twitter is eine typische Erscheinung der Generation ADS & SMS. Für einen Brief zu faul, für einen kompletten Satz zu dumm und für korrekte Grammatik zu cool.  (http://german-bash.org/293437)
