### ISSUE TITLE
Prevent Autoscaling of Gauges

### ISSUE THREAD

**Issue by Pogs2004** [mcrossley/SteelSeries-Weather-Gauges#21]
I am using the SteelSeries gauges with Weewx and RTGD on a 3 second update as a stand-alone weather display on an old iPad. It looks great, however the constant rescaling of the gauges for no apparent reason is a real problem. Glancing at the display it should be possible to determine the temperature and other readings by looking at the needle position without looking at the numbers. Unfortunately this is not the case due to the autoscaling.

The lowest temperature my station has recorded is -4.6ºC and the highest (which was a very rare one-off) was 25.7ºC, so the scale of -10ºC to +30ºC is perfect, and I have that set in the script, however it keeps rescaling to -20ºC to +20ºC for no apparent reason. The highest and lowest dew point was 18.8ºC and -6.9ºC respectively, and I only display dew point on the second gauge so the other values are of no interest.

I can cope with the wind speed gauge rescaling, but even then I would like it to remain 0 - 60mph and only rescale when it goes over 60mph. Pressure, UV and solar radiation seem to stay at the values I have set.

Is there a way to prevent this?

**Comment by mcrossley** [comment]
Hi, yes you can disable the auto-scaling, but you will have to edit the gauges.js file.

For the temperature gauge, set your desired min and max scale values at lines 773,774
```
params.minValue = -10;
params.maxValue = 30;
```

Then you need to comment out the auto-scaling code that changes the gauge; lines 866 to 870
```
if (cache.minValue !== ssGauge.getMinValue() || cache.maxValue !== ssGauge.getMaxValue()) {
  ssGauge.setMinValue(cache.minValue);
  ssGauge.setMaxValue(cache.maxValue);
  ssGauge.setValue(cache.minValue);
}
```

You may also need to add an extra parameter to disable "nice scaling", which is where the gauge changes the requested min/max values slightly to achieve nicely spaced numbers and tick marks.
If you need to do this then at line 738 insert a new line...
```
params.niceScale = false;
```

**Comment by Pogs2004** [comment]
That's great, thank you! I have fixed the temp and dew point scales to -10 +30 and much easier to glance at. It puts 10ºC at the 12 0'clock position which is perfect.

**Comment by mcrossley** [comment]
OK, great.
