### ISSUE TITLE
Zambretti forecast in WeeWX SteellSeries

### ISSUE THREAD

**Issue by remy-lavabre** [mcrossley/SteelSeries-Weather-Gauges#22]
Good morning,

The SteelSeries skin leaves the possibility of displaying weather forecasts.
The gauge-data.txt.tmpl file contains the following lines:

## if forecasting is installed, report the Zambretti forecast
#if $varExists('forecast.zambretti')
#set $fc = $forecast.label('Zambretti', $forecast.zambretti.code)
#else
#set $fc = 'Prévisions météo indisponibles'
#end if

Hence my question: how should we activate these “Zambretti” weather forecasts?

THANK-YOU !

**Comment by mcrossley** [comment]
Sorry, I have no idea, and I do not use weewx. That file was created by one of the weewx devs. You need to ask this question on the weewx forum.
