### ISSUE TITLE
Background Image on Wind Rose Gauge

### ISSUE THREAD

**Issue by Pogs2004** [mcrossley/SteelSeries-Weather-Gauges#23]
I am trying to add a background image to the wind rose gauge, however it doesn't seem to follow the same format as the other gauges. I can't find any other reference to g_imgSmall. If I uncomment background section and change g_imgSmall to logoSmall.png (or even leave it as g_imgSmall) it breaks the script:

```
                    // Optional - add a background image
                    
                     if (logoSmall.png !== null) {
                        var drawSize = g_size * 0.831775;
                        var x = (g_size - drawSize) / 2;
                        buffers.ctxBackground.drawImage(logoSmall.png, x, x, cache.gaugeSize, cache.gaugeSize);
                    }
```
I would like to add the same image as I use on the wind direction gauge.

![No Wind Small](https://github.com/mcrossley/SteelSeries-Weather-Gauges/assets/17429893/29677923-e6de-4ab9-93ff-ac4f14b22db5)

**Comment by mcrossley** [comment]
It's not possible. The wind rose is not a "real" SteelSeries gauge, its one I made up using SteelSeries components. The wind rose (which is created by separate graphing package) is already plotted as the background to the empty gauge.
